sonar.projectKey=secure-cicd-pipeline
sonar.projectName=secure-cicd-pipeline
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/.git/**,**/node_modules/**,**/venv/**,**/__pycache__/**,**/*.min.js,**/reports/**
